[workspace]
members = [
    ".",
    "atmosphere-macros",
    "atmosphere-core",
]

[workspace.package]
version = "0.0.1-alpha.2"
license = "Apache-2.0"
edition = "2021"
authors = ["Mara Schulke <mara@hemisphere.studio>"]
repository = "https://github.com/hemisphere-studio/atmosphere"
keywords = ["sqlx", "postgres", "database", "orm", "backend"]

[workspace.dependencies]
atmosphere-core = { version = "=0.0.1-alpha.2", path = "atmosphere-core" }
atmosphere-macros = { version = "=0.0.1-alpha.2", path = "atmosphere-macros" }
async-trait = "0.1"
sqlx = { version = "0.6", features = ["chrono"] }
thiserror = "1"

[package]
name = "atmosphere"
readme = "README.md"
description = "Atmosphere for sustainable growth of sqlx projects"
documentation = "https://docs.rs/atmosphere"
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[[example]]
name = "forest"
path = "examples/forest/main.rs"

[features]
default = ["runtime-tokio-rustls", "postgres"]
runtime-actix-native-tls = ["sqlx/runtime-actix-native-tls"]
runtime-async-std-native-tls = ["sqlx/runtime-async-std-native-tls"]
runtime-tokio-native-tls = ["sqlx/runtime-tokio-native-tls"]
runtime-actix-rustls = ["sqlx/runtime-actix-rustls"]
runtime-async-std-rustls = ["sqlx/runtime-async-std-rustls"]
runtime-tokio-rustls = ["sqlx/runtime-tokio-rustls"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite"]

[dependencies]
atmosphere-core.workspace = true
atmosphere-macros.workspace = true
async-trait.workspace = true

[dev-dependencies]
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1", features = ["macros"]}
tokio-test = "0"
