name: CI

on:
  push:
    branches: ["main"]
  pull_request:

env:
  MINIMUM_LINE_COVERAGE_PERCENT: 0

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add rustfmt
      - run: cargo fmt --check --all -- --features atmosphere-core/sqlite
      - run: cargo fmt --check --all -- --features atmosphere-core/postgres
      - run: cargo fmt --check --all -- --features atmosphere-core/mysql

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update && rustup component add clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --workspace --features atmosphere-core/sqlite -- -D warnings -D clippy::all
      - run: cargo clippy --all-targets --workspace --features atmosphere-core/postgres -- -D warnings -D clippy::all
      - run: cargo clippy --all-targets --workspace --features atmosphere-core/mysql -- -D warnings -D clippy::all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: "true"
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./tests/postgres.yml"
      - run: rustup update
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --workspace --features atmosphere-core/postgres
        env:
          RUST_BACKTRACE: 1
          DATABASE_URL: postgres://atmosphere:atmosphere@localh/ost:5432

  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo install typos-cli || true
      - run: typos
